import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            // Install KiClient bridge as early as possible
            (function() {
              const existing = window.kiclient || {};
              const previousPost = typeof existing.postMessage === "function" ? existing.postMessage.bind(existing) : null;
              
              existing.postMessage = function(incoming) {
                // Store message for later processing
                if (!window.kicadMessages) {
                  window.kicadMessages = [];
                }
                window.kicadMessages.push(incoming);
                
                if (previousPost) {
                  previousPost(incoming);
                }
              };
              
              window.kiclient = existing;
            })();
          `
        }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
